### ISSUE TITLE
CMD + A and try to unorder-list it erases the selected block...

### ISSUE THREAD

**Issue by mdominguez** [craftcms/redactor#66] opened 2018-07-04 13:02 UTC
god damn it :) didn't have these issues with Redactor in Craft 2 [view screenrecording](https://cl.ly/shnv)

**Comment by andris-sevcenko** [comment] 2018-07-10 10:48
I'm unable to reproduce this. What Redactor plugin version are you using? Can you reproduce this on https://imperavi.com/redactor/ ?

**Comment by mdominguez** [comment] 2018-07-15 06:50
Yep, just paste 2 paragraphs of lorem ipsum and then CMD / CTRL + A to select everything. Then click to make a list of it and nothing happens. Probably related to #65 :)

**Comment by andris-sevcenko** [comment] 2018-07-16 10:18
Yup, definitely related. Closing this one as a duplicate of #65.

**Closed by andris-sevcenko** 2018-07-16 10:18 UTC
