### ISSUE TITLE
Redactor dropdown z-index issue

### ISSUE THREAD

**Issue by LarsDol** [craftcms/redactor#216] opened 2020-03-18 13:39 UTC
I'm running into an issue where I can't use the dropdowns redactor provides when, for example, clicking the _format_ button. 

This specifically happens when the redactor field has been contained within another craft modal, like the image modal.

**To reproduce:**
1. Add an _assets_ field to your page
2. Add a redactor field to this specific asset group (In my case that's a _credits_ field)
3. Upload an image to your field
4. Double-click the image to open the image modal
5. Enter some text in the redactor (credits) field that's contained within the modal
6. Select your text and try to use the _format_ button

Now you'll see that the formatting dropdown is positioned below the modal, and thus not usable.

If I check the CSS properties of both, the modal has a `z-index` of `100` while the redactor dropdown is set to `2 !important`.

For now I'll overwrite it using custom CSS styles in the CP, but I think it's nice to fix this altogether 🙂

Thanks!
Lars

**Comment by brandonkelly** [comment] 2020-03-18 21:33
This looks like a duplicate of #215, which we just fixed today in Redactor 2.6.1. Can you please try updating and let me know if that fixes it for you?

**Closed** 2020-03-18 21:34 UTC
Labels: duplicate
