### ISSUE TITLE
Safari Freezing Up when clicking into Redactor field

### ISSUE THREAD

**Issue by agrigg** [craftcms/redactor#169] opened 2019-10-11 19:00 UTC
I'm using Craft 3.3.7 and we have a Redactor field in a Matrix and when editing the page in Safari if we click into that Redactor field Safari freezes and the beach ball spins. We have to Force Quit Safari. It works fine in Chrome. Our client reported it and I have been able to reproduce it on my machine as well.

Here are the settings for this Redactor field in the matrix:

<img width="791" alt="Redactor Settings" src="https://user-images.githubusercontent.com/519580/66677495-be34d280-ec37-11e9-9e0f-318aa191102d.png">

**Comment by stevenvandemoortele** [comment] 2019-11-14 10:08
Can confirm same issue using Safari Version 13.0.2 (14608.2.40.1.2)
Craft version 3.1.29
Redactor plugin version 2.3.3.2

**Comment by meredevelopment** [comment] 2019-12-04 12:42
I've just hit this issue. As soon as I select 'format' from within a Redactor field I get the beachball and have to force-quit. 

Mojave 10.14.6
Craft 3.3.17
Redactor 2.4.0

**Comment by MisterMike** [comment] 2019-12-16 16:41
Same issue, I cant select a title inside redactor, Safari immediately blocks.

Mojave 10.14.6
Version 13.0.3 (14608.3.10.10.1)
Craft 3.3.18.2
Redactor 2.4.0

Editing in source code mode works fine.

**Comment by andris-sevcenko** [comment] 2020-02-05 14:35
@MisterMike is this still the case with Craft 3.4.x and Redactor 2.5?

**Comment by andris-sevcenko** [comment] 2020-02-06 08:12
Closing this for now, will reopen if still an issue.

**Closed by andris-sevcenko** 2020-02-06 08:12 UTC

**Comment by MisterMike** [comment] 2020-02-06 08:57
Sorry for the late reply. Seems to work fine in the current (mentioned) Versions - thanks !

**Comment by totov** [comment] 2020-04-01 16:25
I'm getting this now when I try to format selected content. It's a Redactor field (using the _Standard_ Redactor Config option) within a Matrix block.

When I add content (type manually, or paste) and then make a selection and go to _Format > Heading 4_ the UI freezes up and I need to force quit Safari. Happening consistently every time I do this.

macOS Mojave 10.14.6
Safari 13.0.2
Craft CMS (Pro) 3.4.12
Redactor 2.6.1

**Comment by brandonkelly** [comment] 2020-04-02 09:59
@totov Please post the contents of `config/redactor/Standard.json`

**Comment by totov** [comment] 2020-04-02 10:01
@brandonkelly Here you go:

```
{
  "buttons": ["formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video"],
  "plugins": ["fullscreen", "video"],
  "linkNewTab": true,
  "toolbarFixed": true
}

```

I haven't touched anything in there, so it's fresh from install.

**Comment by brandonkelly** [comment] 2020-04-02 10:09
Huh, I’m unable to reproduce, but I’m using macOS 10.15 Catalina with Safari 13.1. Is that version of Safari available to Mojave?

**Comment by totov** [comment] 2020-04-02 11:03
It is - I'll update to 13.1 and see if that resolves the issue.

**Comment by totov** [comment] 2020-04-02 11:46
That update seems to have stopped the freeze happening. Thanks @brandonkelly.

**Comment by brandonkelly** [comment] 2020-04-02 17:11
Good to hear!
