### ISSUE TITLE
Plugin buttons are not shown in craft 3.10.0.1

### ISSUE THREAD

**Issue by arjankruithof** [craftcms/redactor#59] opened 2018-06-06 18:49 UTC
```
"plugins": [
        "clips",
        "fullscreen"
    ],
```

**Comment by lukebailey** [comment] 2018-06-07 09:49
Experiencing the same issue - thought I was going mad!

**Comment by andris-sevcenko** [comment] 2018-06-07 09:57
What Redactor plugin version are you using? Did the buttons show up prior to 3.10.0.1?

**Comment by lukebailey** [comment] 2018-06-07 10:34
I am on redactor version 2.1.0, can't be sure if this was also a problem with Craft 3.10.0 as well.

**Comment by lukebailey** [comment] 2018-06-07 14:05
This is now resolved with Craft 3.0.10.2

**Comment by lukebailey** [comment] 2018-06-07 14:46
Actually the issue is now more severe, whilst editing the plugin is fine but upon saving the text disappears and can no longer be seen/edited:

![image](https://user-images.githubusercontent.com/3185073/41107278-f665c084-6a69-11e8-955b-645538993406.png)

**Comment by andris-sevcenko** [comment] 2018-06-08 08:07
Closing this, then? If anyone is still experiencing this with Craft 3.0.10.3, let me know.

**Closed by andris-sevcenko** 2018-06-08 08:07 UTC
