### ISSUE TITLE
Image resize handle is not positioned correctly sometimes

### ISSUE THREAD

**Issue by timoschwarzer** [craftcms/redactor#337] opened 2021-08-04 10:16 UTC
### Description
Sometimes, the image resize handle is displayed in an incorrect Redactor editor. I've not yet figured out when this happens but I can reproduce it as follows:

### Steps to reproduce

1. Have a matrix with one field that only has a Redactor field and another field that has a plain text field + a Redactor field
2. Create a new entry and insert an image into the Redactor-only block: handle works
   <img src="https://user-images.githubusercontent.com/8849554/128163666-00da6159-8216-4dc6-ad98-9653502fe465.png" width="400">
3. Create another Redactor-only block and insert an image: handle works (optional, just to proof that this doesn't happen on any non-first Redactor block)
   <img src="https://user-images.githubusercontent.com/8849554/128163875-9d6bce85-7761-4446-8f48-cddda9a22b93.png" width="400">
4. Create a plain text + Redactor block and insert an image: handle is on the wrong image:
   <img src="https://user-images.githubusercontent.com/8849554/128164083-13b069fe-110a-46ca-a217-088edd96222b.png" width="400">

### Additional info

- Craft version: 3.7.7 Pro
- PHP version: 8.0.9
- Database driver & version: PostgreSQL 12.6
- Plugins & versions: Redactor 2.8.8 only

**Comment by andris-sevcenko** [comment] 2022-01-28 14:12
I am unable to reproduce this locally on the version that will be released next week (2.9). It will also include an updated version of Redactor, so maybe that factors into this.

If you can reproduce this after updating to 2.9, let me know!

**Closed by andris-sevcenko** 2022-01-28 14:12 UTC
Labels: bug
