### ISSUE TITLE
Image popup is empty

### ISSUE THREAD

**Issue by ruudvdboom** [craftcms/redactor#111] opened 2019-01-16 16:45 UTC
After updating to Craft 3.1

The popup doesn't show any images when using the image button. The field has the correct settings to use all the volumes and the volumes do have images in it.

**Comment by andris-sevcenko** [comment] 2019-01-16 17:45
Duplicate of #109 

Should be a release to fix that today. Sorry for the delay :(

**Closed by andris-sevcenko** 2019-01-16 17:45 UTC
