### ISSUE TITLE
Links not editing correctly

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/redactor#50] opened 2018-05-15 19:11 UTC
Hard one to explain so here's a video!

https://youtu.be/8L0UkFF2YXo

When trying to edit a link, upon saving, link is duplicated and saves over link before the one being edited.

Any thoughts?

**Comment by andris-sevcenko** [comment] 2018-05-15 19:48
In essence this is a duplicate of #48

**Closed by andris-sevcenko** 2018-05-15 19:48 UTC

**Comment by DynamiteGoesBoom** [comment] 2018-05-15 19:50
Will you re-open the other task @andris-sevcenko?

**Comment by andris-sevcenko** [comment] 2018-05-16 05:26
Hmm. If you type `$R.version` in your browser's dev console, what do you get?

**Comment by DynamiteGoesBoom** [comment] 2018-05-16 17:34
Client is also reporting this:

> I can link to a url now but not an entry and it’s actually worse because the modal doesn’t disappear but every-time you click save it’s adding that text as a link on the line above.

**Comment by jameskrill** [comment] 2018-05-16 21:31
@andris-sevcenko 3.0.9

**Comment by andris-sevcenko** [comment] 2018-05-17 05:13
@DynamiteGoesBoom @jameskrill is it possible to get access to a site where I can see this behaviour? I'm not able to reproduce this locally (as opposed to I was able to reproduce the original issue in this ticket pre-3.0.9)

**Comment by andris-sevcenko** [comment] 2018-05-17 05:14
If the answer is yes, then can you send the credentials to support@craftcms.com referencing this ticket?

**Comment by DynamiteGoesBoom** [comment] 2018-05-17 18:07
@andris-sevcenko Sent!

**Comment by andris-sevcenko** [comment] 2018-05-18 17:08
FTR this is a bug with Redactor 3.0.9 and I've submitted a bug report to Imperavi.
