### ISSUE TITLE
Fullscreen mode obscured by Craft menu panel

### ISSUE THREAD

**Issue by stevehurst** [craftcms/redactor#270] opened 2020-09-14 12:54 UTC
### Description

The sidebar / menu obscures Redactor when fullscreen mode is enabled.

<img width="1234" alt="Screen Shot 2020-09-14 at 7 47 09 AM" src="https://user-images.githubusercontent.com/20077/93088344-67adf080-f65f-11ea-910b-afa642f79b86.png">

### Additional info

- Craft version: 3.5.9
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.31
- Plugins & versions: Redactor 2.7.4

**Comment by andris-sevcenko** [comment] 2020-09-22 09:05
I'm unable to reproduce this in Craft 3.5.11. Can you check if the issue still persists for you on 3.5.11?

**Comment by andris-sevcenko** [comment] 2020-12-08 09:47
Closing this, as it's most likely fixed and there's been no activit.

**Closed by andris-sevcenko** 2020-12-08 09:47 UTC
Labels: bug
