### ISSUE TITLE
Issue with Redactor loosing some formatting when saving the page

### ISSUE THREAD

**Issue by franciurachel** [craftcms/redactor#237] opened 2020-06-30 09:33 UTC
First of all, I am not sure whether it's an issue with Redactor or Craft or both.
For some users, when on Chrome, but not happening if in Incognito mode, heading formatting does not save, unless pressing enter or space after the text.

1. Create a text
2. Apply h2 formatting
3. Save the page
4. Formatting disappears

Regardless of Purify HTML and Clean Up HTML advanced configuration. (Tried to change it to solve the problem).

Redactor Config:
{
  "buttons": ["html", "format", "bold", "italic", "unorderedlist", "orderedlist", "link", "file"],
  "plugins": ["fullscreen"],
  "linkNewTab": true,
  "toolbarFixed": true,
  "formatting": ["h2", "h3", "h4", "h5", "h6", "p"]
}

Craft 3.3.01 and 3.2.8.
Redactor 2.3.3.2

**Comment by Jones-S** [comment] 2020-06-30 12:04
I have maybe a related issue to this:
I have this config:
```
{
  "buttons": ["formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video", "html"],
  "plugins": ["fullscreen", "video"],
  "linkNewTab": true,
  "toolbarFixed": true,
  "imagePosition": true,
  "imageFloatMargin": true,
  "imageResizable": true,
  "breakline": true,
  "formattingAdd": {
    "Highlight": {
      "title": "Highlight Paragraph",
      "api": "module.block.format",
      "args": {
        "tag": "p",
        "class": "redactor-highlight",
        "type": "add",
        "style": {
          "font-weight": "bold",
          "color": "blue"
        }
      }
    }
  }
}

```

If I select some text and apply the custom styling `Highlight Paragraph` it appears quickly styled in blue and bold, but when saving or viewing the `html` view, the styling disappears and no extra class is saved in the actual text...

**Comment by Jones-S** [comment] 2020-06-30 13:48
Videolinks get lost too.
Youtube and Vimeo first (directly after pasting) get displayed as video-previews, when saving the content is stripped of this kind of media... :(

FYI:
```json
// composer.json
{
...
  "require": {
        "php": "7.0.* || 7.1.* || 7.2.*",
        "craftcms/cms": "3.5.x-dev",
        "craftcms/element-api": "2.6.0",
        "craftcms/feed-me": "4.2.2",
        "craftcms/redactor": "2.6.0.1",
        "guzzlehttp/guzzle": "~6.0",
        "j7mbo/twitter-api-php": "1.0.6",
        "mmikkel/cp-field-inspect": "1.1.2",
        "nystudio107/craft-seomatic": "^3.2.43",
        "putyourlightson/craft-cp-style-guide": "1.0.2",
        "sebastianlenz/linkfield": "2.0.x-dev",
        "spicyweb/craft-neo": "^2.6.1",
        "verbb/field-manager": "2.1.1",
        "vlucas/phpdotenv": "^2.4.0",
        "wearelucid/craft-netlify-deploy-button": "^1.1.2"
    },
 ...
}
```

**Comment by andris-sevcenko** [comment] 2022-01-26 10:58
Testing the original issue by @franciurachel locally on a pending 2.8.9 version of this plugin, I can't reproduce this, so I'll close this issue.

@Jones-S there's not much we can do about the video previews, as Redactor displays the entered content and HTML purifier sanitizes the value upon save.

If you are still experiencing the custom styling issue, please, open a new issue!

**Closed by andris-sevcenko** 2022-01-26 10:58 UTC
