### ISSUE TITLE
Inserting links (link to entry) broken. this.caret undefined

### ISSUE THREAD

**Issue by stenvdb** [craftcms/redactor#61] opened 2018-06-14 15:33 UTC
When inserting a link (link to entry) I get a JavaScript error when slecting an entry. 
```TypeError: this.caret is undefined```
In `redactor.js:12486:12`. I'm on the latest version of redactor and Craft 3.0.10.3. The site has two locales (= 2 sites).

**Comment by andris-sevcenko** [comment] 2018-06-15 08:11
When you say "latest version" is that the latest released version of the latest commit to the repository?

**Comment by stenvdb** [comment] 2018-06-15 08:12
Ah yes, sorry if I wasn't specific, I'm at 2.1.0

**Comment by andris-sevcenko** [comment] 2018-06-15 08:16
Hmm, I'm unable to reproduce on that one either. Can you upload a screencast so I can see if I'm maybe missing a step or I'm doing it differently?

**Comment by andris-sevcenko** [comment] 2018-06-18 13:38
I'm unable to reproduce on your site, either. Have you tried clearing your browser's cache? If you type `$R.version` in your developer console, what do you get?

**Comment by stenvdb** [comment] 2018-06-18 13:47
3.0.9,
I just tested this in Chrome, where it actually works. I'm getting the error in Firefox. Can you reproduce it in Firefox (latest version)?

**Comment by andris-sevcenko** [comment] 2018-07-06 10:04
@stenvdb Sorry for the long delay. I'm still unable to reproduce on Firefox 61.0.1

**Comment by stenvdb** [comment] 2018-07-06 10:12
Weird.. I still have this issue on Firefox 61.0.1. Have you tested this on my site with the credentials I sent over? I can reproduce this error even when I login using a tool like browserstack.

**Comment by andris-sevcenko** [comment] 2018-07-13 10:45
@stenvdb finally was able to reproduce. We just released Redactor 2.1.1, can you update to that and see if that fixes the issue?

**Comment by stenvdb** [comment] 2018-07-13 11:40
Hi @andris-sevcenko unfortunately not :( Updated to 2.1.1 but exact same error in the same place still occurs. I updated our live site as well, so if you find the time, you can still test with the credentials I sent you a while back.

**Comment by andris-sevcenko** [comment] 2018-07-13 14:09
Okay, was able to reproduce locally, finally. Looking into it.

**Comment by andris-sevcenko** [comment] 2018-07-16 10:17
@stenvdb traced it down to a bug in Redactor itself (even the latest 3.1). I submitted a bug report, hopefully it's fixed soon.

**Comment by andris-sevcenko** [comment] 2018-08-20 13:37
Still unfixed as of Redactor 3.1.1

**Comment by andris-sevcenko** [comment] 2018-08-21 07:53
@stenvdb to clarify, you should not be seeing `this.caret is undefined` error, but your links might exhibit the symptoms outlined in #69, so closing this as a duplicate now.

**Closed** 2018-08-21 07:53 UTC
Labels: bug

**Comment by stenvdb** [comment] 2018-08-21 14:03
@andris-sevcenko Perfect, will subscribe to #69 so I'll know when Redactor releases a fix. Thanks for the heads up!
