### ISSUE TITLE
Link to an entry has disappeared

### ISSUE THREAD

**Issue by EmptyStreets** [craftcms/redactor#32] opened 2018-05-01 21:16 UTC
Since the last update (redactor 3). 

      "buttons": [
          "formatting",
          "bold",
          "italic",
          "unorderedlist",
          "orderedlist",
          "link",
          "html"
      ],

shows only the default linking option (manual).

![screenshot-2018 05 01-23-16-44](https://user-images.githubusercontent.com/1551388/39494197-c2277f92-4d95-11e8-9f0b-0e89880f5552.png)

**Comment by andris-sevcenko** [comment] 2018-05-02 07:03
I'm unable to reproduce this. 

* Have you tried clearing the browser's cache?  
* Are you seeing any errors in the browser console?  
* Do you have more than one section with URLs enabled?

**Comment by lukeyouell** [comment] 2018-05-02 09:33
@EmptyStreets @andris-sevcenko I can replicate this in 2.0.0 but updating to 2.0.0.1 fixes it

**Comment by andris-sevcenko** [comment] 2018-05-02 09:37
Ah, then it is what I thought it might be. Closing this now, then.

**Closed by andris-sevcenko** 2018-05-02 09:37 UTC
