### ISSUE TITLE
Links that were working fine on multi-site setup are suddenly all pointing to the first (wrong) site

### ISSUE THREAD

**Issue by bencresty** [craftcms/redactor#373] opened 2022-02-24 18:44 UTC
### Description

I have a multi site setup running fine for quite a long time now and had no issues when updating either craft nor the plugins related to links inside redactor. But somehow all links on the second site (which is a different locale of the same site here) are now suddenly pointing to the wrong site (the first site).

The setup has both Redactor as redactor-anchors plugin installed, so I'm not sure which of these actually caused this or perhaps something inside Craft itself had changed in some of the upgrades, but I just found out about this issue.

Can't tell it wasn't particularly nice to notice something that was working for months/years was suddenly broken. I have upgraded everything to the latest versions now and am now restoring ALL (!!) links on that second site, which is obviously not a fun thing to do for all these pages.

I'm really hoping this issue is fixed in some of the latest updates, but don't remember seeing any of this in the change logs. Also there was not mentioning about breaking changes or upgrade instructions needed. So that's why I'm not sure this bug is solved and open this issue.

I've also seen another issue that looks related, but is different here: https://github.com/craftcms/redactor/issues/372 .
Difference is that the other issue talks about wrong suggestions, where this issue is about actually broken links-behaviour.

It looks to me that some of the latest changes in either Craft, redactor or redactor-anchors was a breaking change. Could somebody knowing about this issue perhaps tell me if this is the case and I don't need to re-adjust all links of these sites again at a later time?
That would be highly appreciated as this is no fun!! :(

[edit] I see now that not only 'normal' entry-links are broken, but also links to anchors. All these were working fine before. Links with anchors are now suddenly trying to go to the home page with the hashtag added to it, instead of the entry they were previously set to.

### Steps to reproduce

1. Have a working multi-language site
2. Install updates to Craft en plugins (which don't have mentioned breaking changes)
3. See that all links on the second site are now pointing to the (wrong) first site

### Additional info

- Craft version: No clue when this started. This issue could be there for longer, but when I noticed it Craft was at version 3.7.26) 
- PHP version: 8.x
- Database driver & version: Mysql/Mariadb
- Plugins & versions: 
 No clue when this started. This issue could be there for longer, but when I noticed it  `redactor` plugin was at 2.10.4 and `edactor-anchors` plugin was at 1.3.2 (which they are still at today)

**Comment by brandonkelly** [comment] 2022-02-24 23:31
Could be either #187 (v2.5) or #249 (v2.9).

What are the base URLs of your sites? Which one is getting linked to unexpectedly?

For the links, are you entering the URLs manually, or are you using the entry selector modal?

**Comment by bencresty** [comment] 2022-02-25 01:59
Thanks for the quick response. 

> Could be either #187 (v2.5) or #249 (v2.9).

I fixed all links on the website here now. Does this mean I can trust the links to stay the same now because the breaking change has been executed and is finished? 
 
> What are the base URLs of your sites? Which one is getting linked to unexpectedly?

There are two sites, which is basically one site in two languages in this case (not sure about other projects here tho, need to check). The main site has format `domain.xxx` and the second site has `domain.xxx/xx` (2 char locale code).
What was happening is that all links in redactor fields on the main site were fine (except for one or two links to anchors I believe). The issues were mainly on the second site (which has the same domainname, but added to that a `/xx` (local code) for the other language. These links (so on the second site) were not ending with `@2:url`, but with `@1:url`, so they weren't pointing to the second sites entries, but to the first sites entries, so the wrong site.

> For the links, are you entering the URLs manually, or are you using the entry selector modal?

All links to internal pages were entered using the entry selector for links. They were all pointing to the right pages on the right site and were never changed by users after that. Neither were the sites changed.

Hope this helps!

**Comment by andris-sevcenko** [comment] 2022-02-25 08:07
If the links were added using the entry selector, then they get converted to an element reference on saving, which already includes the site id.

It's unclear how that could have changed in the DB values for every entry, though? Do you have some older DB backups where you could verify that this site id changes for the links at some point in time?

**Comment by bencresty** [comment] 2022-02-25 12:16
> Do you have some older DB backups where you could verify that this site id changes for the links at some point in time?

For that I don't even need to open the database; it's right there in the Redactor field when editing the link: it said `@1:url` at the end, where it should say `@2.url`.

**Comment by andris-sevcenko** [comment] 2022-02-25 12:35
There's still little indication as to why this change happened, so, either pinpointing it in time or place would be helpful.

The first step would be to, then, to find an entry on your site that has the wrong URL and see what the element reference is in the database for that field and how is that rendered by the reactor field in the CP.

If the site ID is already wrong in the database, then the next step in an ideal world is to use older DB backups and find out whether that's always been the case.

If the Site ID, for example, is _missing_ altogether in the DB, then that would indicate some logic error.

Another potential mischief generator was the 2.9.0 release, which didn't always select the right site in the entry selector modal - that behavior was corrected today in the 2.10.5 release.

**Comment by brandonkelly** [comment] 2022-02-25 13:05
Is the Redactor field translatable?

**Comment by bencresty** [comment] 2022-02-25 17:41
> Is the Redactor field translatable?

Yes, it's set to 'Translate for each site' (otherwise it could've never worked before).

Also it's inside a block type inside a Matrix Block, set to 'Only save blocks to the site they were created in'.

Just a thought: could the issue be that there was a 'fallacy' (not sure if this translated word is not right tho, sorry if not) thinking that different site should always have a different domain name? As the domain name for both sites is exactly the same of course, as only the locale segment after it changes...

For now: thanks for the quick responses and have a nice weekend!

**Comment by brandonkelly** [comment] 2022-02-25 23:30
I can only think of two possibilities:

- It was the same bug as #372. Authors were editing Site B, but Redactor was incorrectly showing them entries from Site A; or…
- It’s only happening for brand new entries, where the initial content you enter will be copied to all of the entry’s sites, regardless of your fields’ translation settings. In which case, the links pointing to Site A would be copied over to Site B, but still linking to entries in Site A (as the reference tags explicitly include the target site, as of Redactor 2.5). Then, even if the content was edited from Site B later, maybe the link URLs weren’t ever “fixed” to point to Site B URLs.

I’m going to go ahead and close this, as things appear to be working as intended in our testing (at least after fixing #372). If you find any new examples of this happening and can come up with steps to reproduce, please let us know and we will look into it from there.

**Closed by brandonkelly** 2022-02-25 23:30 UTC
Labels: bug
