### ISSUE TITLE
Text linking issues

### ISSUE THREAD

**Issue by mortscode** [craftcms/redactor#379] opened 2022-03-21 16:09 UTC
### Description
Experiencing an issue when we select text and link it to an entry. Particularly when linking multiple list items to different entries.

### Steps to reproduce

1. Add a list of items to a redactor rich text field
2. Select and convert the items into a bulleted list
3. Select the first bullet and link it to an entry
4. Select the second bullet and link it to a different entry

-- At this point, we're noticing that the 1st bullet is replaced by the 2nd bullet's link and the 2nd bullet remains unchanged.

### Additional info

- Craft version: 3.7.37
- PHP version: 7.3
- Database driver & version: mysql
- Plugins & versions:
```
        "craftcms/cms": "3.7.37",
        "vlucas/phpdotenv": "^2.4.0",
        "clubstudioltd/craft-asset-rev": "6.0.2",
        "craftcms/redactor": "2.10.5",
        "sebastianlenz/linkfield": "1.0.25",
        "craftcms/contact-form": "2.3.0",
        "craftcms/contact-form-honeypot": "1.0.2",
        "dolphiq/redirect": "1.1.1",
        "nystudio107/craft-seomatic": "3.4.27",
        "craftcms/postmark": "2.1.0",
        "craftcms/element-api": "2.8.4",
        "servd/craft-asset-storage": "2.5.1",
        "mortscode/feedback": "^1.0"
```

**Comment by mortscode** [comment] 2022-03-21 16:18
I rolled Redactor back to `v2.10.5` and the problem persists.

**Comment by mortscode** [comment] 2022-03-21 16:24
https://user-images.githubusercontent.com/3239582/159305485-58294420-f73f-480d-bdbb-f1fc22099b35.mov

**Comment by mortscode** [comment] 2022-03-21 19:21
Here's my Redactor config for that field:
```
{
    "buttons": [
        "formatting",
        "bold",
        "italic",
        "underline",
        "lists",
        "link",
        "html"
    ],
    "formatting": ["p"],
    "formattingAdd": {
        "headline": {
            "title": "H2",
            "api": "module.block.format",
            "args": {
                "tag": "h2",
                "class": "post-text__headline"
            }
        },
        "subhead": {
            "title": "H3",
            "api": "module.block.format",
            "args": {
                "tag": "h3",
                "class": "post-text__subhead"
            }
        }
    },
    "linkNewTab": true,
    "toolbarFixed": true
}
```

**Comment by mortscode** [comment] 2022-03-21 23:23
The problematic behavior persists with any list or even non-bulleted items that are on separate lines. However, within a single paragraph, i can select text and link it and then select different text (within the same paragraph) and the linking goes as expected.

With this in mind, I am able to select text in a list item and link it as expected on the condition that I don't select ALL of the text. 

### Like so:

https://user-images.githubusercontent.com/3239582/159378890-b1e0aa88-0bd3-47d7-b2cf-8e4e26bdec94.mov

**Comment by andris-sevcenko** [comment] 2022-03-31 09:40
Thanks for reporting that! This is a duplicate of #374 that we haven't yet been able to solve.

**Closed by andris-sevcenko** 2022-03-31 09:40 UTC
Labels: bug
