### ISSUE TITLE
Handle to resize images disappears after entering and closing Live Preview

### ISSUE THREAD

**Issue by benface** [craftcms/redactor#306] opened 2021-03-12 23:32 UTC
### Steps to reproduce

1. Create a Redactor field with the setting `"imageResizable": true` and add the field to some entry type.
2. Create an entry of that type, and add an image in the Redactor field. Try resizing it. It should work.
3. Enter Live Preview for that entry.
4. Close Live Preview.
5. Click on the image again. Notice you can't resize it, because the handle that used to appear in the lower right corner is no longer there.

### Additional info

- Craft version: 3.6.9
- PHP version: 7.4.14
- Database driver & version: MySQL 8.0.23
- Plugins & versions: Redactor 2.8.5

**Comment by andris-sevcenko** [comment] 2021-03-16 12:11
I can definitely reproduce this - trying to figure out a fix, but I can't promise anything at the moment.

**Comment by andris-sevcenko** [comment] 2021-03-16 12:42
It seems like the plugin is not able to trick Redactor into switching the target element after live preview ends. I'm leaving this one open, but it's not going to be a priority, as it can be worked around and the parts where we go and override some Redactor behavior are the trickiest to change.

**Comment by andris-sevcenko** [comment] 2022-01-27 12:54
This seems to be working for me locally on Craft 3.7.30.1 and a pending Redactor 2.9 release, so closing this one for now. If, after updating to the latest Craft and Redactor (after the 2.9 release this or next week) this still happens, let me know!

**Closed by andris-sevcenko** 2022-01-27 12:54 UTC
Labels: bug
