### ISSUE TITLE
Links with query strings do not work as expected

### ISSUE THREAD

**Issue by LeoWie93** [craftcms/redactor#288] opened 2020-11-24 07:40 UTC
Adding a new link inside a redactor field like `https://example.com?param1=value&param2=value`  are parsed in an unexpected way after pressing add. **Not** saving the entry.

The link will look like this after being added to the text: `https://example.com?param1=value&amp;param2=value`. The `&` is parsed and breaks the link.

Additional info

    Craft version: 3.5.14
    PHP version: 7.4.12
    Database driver & version: MySQL 5.7.32
    Redactor Plugin version: 2.8.3

**Comment by andris-sevcenko** [comment] 2022-01-27 10:45
I'm unable to reproduce this locally on the new version that'll be released either this week or early next week, so closing this now. If the issue persists after updating to the 2.9 version, please let us know!

**Closed by andris-sevcenko** 2022-01-27 10:45 UTC
