### ISSUE TITLE
Table Plugin - Unable to edit tables in Edge

### ISSUE THREAD

**Issue by mikecsmith** [craftcms/redactor#87] opened 2018-08-29 17:45 UTC
Currently in Edge when a table is created using the table plugin content creators are unable to click on a table cell and edit its content in Edge. This is fully repeatable on both our staging site and the table plugin demo here: https://imperavi.com/redactor/plugins/table/

To repeat on the Imperavi demo site:

- Insert a Table using the plugin
- Attempt to click into the table, you do not see a cursor and are unable to enter content

To repeat in Craft:

- Add a table to a Redactor field
- You are able to click on a table field and edit content
- Save the Craft CMS entry
- Go back into the entry and attempt to click on the table, you do not see a cursor and are unable to enter content

OS: Windows 10 Pro 64bit
Browser: Microsoft Edge 42.17134.1.0

**Comment by angrybrad** [comment] 2018-08-29 21:36
Tested on https://imperavi.com/redactor/plugins/table/ using Win10 Pro/64 bit and wasn't able to reproduce on Edge 44.17746.1000.0, but I could on IE 11.1000.177460.0.

Since I'm using a newer Edge version it's likely that resolved the behavior there... can you try updating?

Since it's reproducible on the Imperavi demo site, then there's not much we can do about it until it gets fixed in Redactor, unfortunately.

**Closed by angrybrad** 2018-08-29 21:36 UTC
