### ISSUE TITLE
Redactor table not responding as expected when used inside a matrix

### ISSUE THREAD

**Issue by dansiberry** [craftcms/redactor#172] opened 2019-10-22 12:16 UTC
When using a table in redactor inside of a matrix or Super Table field, the controls for deleting a table and adding rows/column don't behave as expected. 

After creating a table and deleting it, the option to create a table again is greyed out. 
If you click 'Add column' or 'Add row' it inserts the row and column into the DOM outside of the redactor field. 
![Screen Shot 2019-10-22 at 2 14 15 pm](https://user-images.githubusercontent.com/22725282/67284726-7125eb80-f4d6-11e9-9774-d79f52cf37ee.png)

Craft CMS - 3.3.7
Redactor - 3.3.0

Thanks

**Comment by andris-sevcenko** [comment] 2020-02-06 10:22
Can you update both Craft and Redactor plugin to the latest versions and see if you can reproduce? Asking, because I can't reproduce this with a Table inside a Matrix field.

I'll close this issue meanwhile.

If you can reproduce it, can you post a video of how to reproduce this? I'll re-open the issue then.

**Closed by andris-sevcenko** 2020-02-06 10:22 UTC
