### ISSUE TITLE
Links dissapearing after inserting link in highlighted text

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [craftcms/redactor#361] opened 2022-02-08 15:24 UTC
### Description
After upgrading to redactor 2.9.0, if we have a text with a few links and you add another link, highlighting the text, links are removed after inserting the link.

See video [here](https://api.media.atlassian.com/file/cfeadccc-586e-4b85-b9f4-5faff70eba6a/artifact/video_1280.mp4/binary?client=37250196-b428-473c-b69c-9a15eb9572bc&collection=&max-age=2592000&token=eyJraWQiOiJtaWNyb3MtZ3JvdXBcL2ppcmFcLzl2c242OTMwaWNtN24zOGUiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJtZWRpYSIsImNsaWVudElkIjoiMzcyNTAxOTYtYjQyOC00NzNjLWI2OWMtOWExNWViOTU3MmJjIiwiYWNjZXNzIjp7InVybjpmaWxlc3RvcmU6ZmlsZTpjZmVhZGNjYy01ODZlLTRiODUtYjlmNC01ZmFmZjcwZWJhNmEiOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6ZmRkMjc3ZjMtNmE5NC00ZjFhLTg0NGQtMWNkZTJmZTVkYjA5IjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOjFmOTZiN2Y4LTQ1NTQtNDY4Mi04MWI2LTQ5YTdlYjk2NWVlYyI6WyJyZWFkIl19LCJuYmYiOjE2NDQzMzM4ODQsImlzcyI6Im1pY3Jvcy1ncm91cFwvamlyYSIsImV4cCI6MTY0NDMzNDc4NCwiaWF0IjoxNjQ0MzMzODg0LCJqdGkiOiJlMTI2ZGE1Zi0yN2VkLTQ4YzgtOTQwYS02ZDBlNWMzOWNkNWIifQ.lJeCwOhoDvgcUp5uG0H7Z8KdxoNjnFG5jLzuqb81KpEe9dLMGmS1aKBjmasVe32RmkUpYon5DuOX08l5z37tI1ZHXxXTBufEZwBh1-VJktjgFoHUULL360ZPAe6C8agX6DGyhnGfzMrGKaQUrmf2HfDu3wcijvA5OqseBHViFD4ab-07HBCtLvURTYvcd1egaGDAj4LERW909NIuQ6VXRR047VZV0ZYrinXQDlcIR1vakXhVIdF6nRhwAmrM7DhC6SUzmX7yWTYixqZEoypeIwaKh6UGqOMlVhkEcEjJ0eTkGxLYClAfwI8hqDFL89vIzeMyM-vaeP1gJdvUj3E9dQ)

**Comment by nicbou** [comment] 2022-02-08 15:39
Is this a duplicate of #331 ?

**Comment by andris-sevcenko** [comment] 2022-02-09 07:40
I'll close this as a duplicate. FWIW, I've alerted Imperavi of the numerous issues tagged "reactor issue" here.

**Closed by andris-sevcenko** 2022-02-09 07:40 UTC
Labels: bug
