### ISSUE TITLE
Redactor collapses spaces in <pre> tags

### ISSUE THREAD

**Issue by nicbou** [craftcms/redactor#366] opened 2022-02-14 15:44 UTC
### Description

When saving an Entry, Redactor collapses multiple leading spaces into a single space, destroying the desired formatting.

### Steps to reproduce

1. In a preformatted tag, use spaces for indentation
2. Save the post

### Additional info

- Craft version: latest
- PHP version: latest
- Database driver & version: latest
- Plugins & versions: latest

**Comment by nicbou** [comment] 2022-02-14 15:47
If you use tab characters instead, they are converted to 4 spaces when saving, then to a single space when saving again. `&nbsp;` does not work either.

**Comment by andris-sevcenko** [comment] 2022-02-14 15:55
This is a duplicate of https://github.com/craftcms/redactor/issues/314. Disabling the `Replace non-breaking spaces with regular spaces` should fix this for you.

**Closed by andris-sevcenko** 2022-02-14 15:55 UTC
Labels: bug
