### ISSUE TITLE
Inserting another file link changes the text to the previous one value

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/redactor#389] opened 2022-04-27 07:32 UTC
### Description
When we create a second _File_ link, the text is replaced by that of the first link next to it.
See screencast: [https://imgur.com/a/HquKlhk](https://imgur.com/a/HquKlhk).

### Additional info

- Craft version: 3.7.38 + 3.7.39
- PHP version: 7.4.25
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Redactor 2.10.6 + 2.10.7

**Comment by stefanfriedrich** [comment] 2022-04-28 06:58
Same bug with Craft 3.6.17 and Redactor 2.10.6 + 2.10.7

**Comment by smockensturm** [comment] 2022-05-02 10:59
Come on team. For most clients the wysiwig editor is the C in the CMS!!! This is the one field where **most** clients spend **most** of their time. And it is and has been and will be frustrating always, just a fact of life right @brandonkelly ? 

https://github.com/craftcms/redactor/issues

Can any of those bugs be fixed? Seems like a lot.

**Comment by brandonkelly** [comment] 2022-05-03 22:27
We’ll look into this.

@smockensturm Most of these issues are with the JS editor, which is out of our hands. If you want a more stable wysiwyg, you’ll probably have better luck with [CKEditor](https://github.com/craftcms/ckeditor).

**Comment by timkelty** [comment] 2022-05-04 01:54
This is the same issue reported in #384.

Upgrading to latest (2.10.7) fixes this for me, and I'm unable to reproduce any longer.

Can you ensure your browser caches are cleared and also clear control panel resource caches?

**Comment by timkelty** [comment] 2022-05-04 03:27
@romainpoirier @stefanfriedrich Could you test this branch and confirm it is working for you?

```
"craftcms/redactor": "dev-fix-file-replacement",
```

Text/selection replacement should now be fixed for all the `link` button options, as well as the `file` button.

**Comment by stefanfriedrich** [comment] 2022-05-04 05:29
@timkelty sorry, on holidays, can't test before next week.

**Comment by brandonkelly** [comment] 2022-05-04 19:02
2.10.8 is out now with a fix for this.

**Closed by brandonkelly** 2022-05-04 19:02 UTC
Labels: bug
