### ISSUE TITLE
Setting unknown property: craft\redactor\Field::byteLimit

### ISSUE THREAD

**Issue by borndigitalbe** [craftcms/redactor#286] opened 2020-11-13 08:37 UTC
After accepting changes to the project.yaml file in the craft CMS, I get the error Setting unknown property: craft\redactor\Field::byteLimit. 

I can't find anything about this error anywhere and I'm unable to access the website or the admin panel.

**Comment by svenpeeters** [comment] 2020-11-13 09:32
+1

**Comment by superlabbe** [comment] 2020-11-13 10:51
We were able to fix the problem:

Apparently, this was caused by changing a plain text field into a redactor field. Apperently this messes something up with the craft configuration files and throws this error ..

**Comment by jaspertandy** [comment] 2021-04-27 08:23
Surprised this hasn't been addressed by anyone yet. I can't even run project-config/apply as this issue kills everything.

**Comment by andris-sevcenko** [comment] 2022-01-27 10:19
Glad you got it sorted! And sorry for the delayed response :)

**Closed by andris-sevcenko** 2022-01-27 10:19 UTC

**Comment by davidhellmann** [comment] 2022-03-09 11:34
Run into the same problem. How do you fixed that?

**Comment by andris-sevcenko** [comment] 2022-03-09 12:17
@davidhellmann did you try rebuilding project config?

**Comment by davidhellmann** [comment] 2022-03-09 12:19
Sure but the same error occurs :/

![image](https://user-images.githubusercontent.com/764292/157440713-0eb72b25-9331-47c3-b5b5-063bf36c38a8.png)

**Comment by andris-sevcenko** [comment] 2022-03-09 12:25
Ugh, annoying. You can safely remove it from the relevant `.yaml` file, though, and then apply the config.

We'll talk about this internally, but, in general, this is not a Redactor bug - it's a bug where settings get merged instead of being replaced..

**Comment by davidhellmann** [comment] 2022-03-09 12:30
OK, but when I revert to an older commit the issue still exists. 
And the cp is totally broken:

```
An Error occurred while handling another error:
yii\base\UnknownPropertyException: Setting unknown property: craft\fields\Entries::byteLimit in /Users/yyy/xxx/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/yyy/xxx/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('byteLimit', NULL)
#1 /Users/yyy/xxx/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fields\Entries), Array)
#2 /Users/yyy/xxx/vendor/craftcms/cms/src/fields/BaseRelationField.php(219): yii\base\BaseObject->__construct(Array)
#3 [internal function]: craft\fields\BaseRelationField->__construct(Array)
#4 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#5 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\fields\\En...', Array, Array)
#6 /Users/yyy/xxx/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fields\\En...', Array, Array)
#7 /Users/yyy/xxx/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#8 /Users/yyy/xxx/vendor/craftcms/cms/src/helpers/Component.php(111): Craft::createObject(Array)
#9 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Fields.php(595): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#10 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Fields.php(620): craft\services\Fields->createField(Array)
#11 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Fields.php(649): craft\services\Fields->_fields(NULL)
#12 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2178): craft\services\Fields->getAllFields()
#13 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1472): craft\elements\db\ElementQuery->customFields()
#14 /Users/yyy/xxx/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#15 /Users/yyy/xxx/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#16 /Users/yyy/xxx/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#17 /Users/yyy/xxx/vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#18 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1635): craft\db\Query->one(NULL)
#19 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/User.php(461): craft\elements\db\ElementQuery->one()
#20 /Users/yyy/xxx/vendor/yiisoft/yii2/web/User.php(697): craft\elements\User::findIdentity(391)
#21 /Users/yyy/xxx/vendor/craftcms/cms/src/web/User.php(522): yii\web\User->renewAuthStatus()
#22 /Users/yyy/xxx/vendor/yiisoft/yii2/web/User.php(198): craft\web\User->renewAuthStatus()
#23 /Users/yyy/xxx/vendor/yiisoft/yii2/web/User.php(366): yii\web\User->getIdentity()
#24 /Users/yyy/xxx/vendor/craftcms/cms/src/web/User.php(206): yii\web\User->getIsGuest()
#25 /Users/yyy/xxx/vendor/verbb/cloner/src/Cloner.php(51): craft\web\User->getIsGuest()
#26 [internal function]: verbb\cloner\Cloner->verbb\cloner\{closure}(Object(yii\base\Event))
#27 /Users/yyy/xxx/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#28 /Users/yyy/xxx/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\web\\View', 'endBody', Object(yii\base\Event))
#29 /Users/yyy/xxx/vendor/yiisoft/yii2/web/View.php(164): yii\base\Component->trigger('endBody')
#30 /Users/yyy/xxx/vendor/craftcms/cms/src/web/View.php(1161): yii\web\View->endBody()
#31 /Users/yyy/xxx/vendor/yiisoft/yii2/views/errorHandler/exception.php(538): craft\web\View->endBody()
#32 /Users/yyy/xxx/vendor/yiisoft/yii2/base/View.php(347): require('/Users/davidhel...')
#33 /Users/yyy/xxx/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/Users/davidhel...', Array)
#34 /Users/yyy/xxx/vendor/yiisoft/yii2/web/ErrorHandler.php(270): yii\base\View->renderFile('/Users/davidhel...', Array, Object(craft\web\ErrorHandler))
#35 /Users/yyy/xxx/vendor/yiisoft/yii2/web/ErrorHandler.php(127): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#36 /Users/yyy/xxx/vendor/craftcms/cms/src/web/ErrorHandler.php(192): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownPropertyException))
#37 /Users/yyy/xxx/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\base\UnknownPropertyException))
#38 /Users/yyy/xxx/vendor/craftcms/cms/src/web/ErrorHandler.php(71): yii\base\ErrorHandler->handleException(Object(yii\base\UnknownPropertyException))
#39 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\UnknownPropertyException))
#40 {main}
Previous exception:
yii\base\UnknownPropertyException: Setting unknown property: craft\fields\Entries::byteLimit in /Users/yyy/xxx/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/yyy/xxx/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('byteLimit', NULL)
#1 /Users/yyy/xxx/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fields\Entries), Array)
#2 /Users/yyy/xxx/vendor/craftcms/cms/src/fields/BaseRelationField.php(219): yii\base\BaseObject->__construct(Array)
#3 [internal function]: craft\fields\BaseRelationField->__construct(Array)
#4 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#5 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\fields\\En...', Array, Array)
#6 /Users/yyy/xxx/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fields\\En...', Array, Array)
#7 /Users/yyy/xxx/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#8 /Users/yyy/xxx/vendor/craftcms/cms/src/helpers/Component.php(111): Craft::createObject(Array)
#9 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Fields.php(595): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#10 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Fields.php(620): craft\services\Fields->createField(Array)
#11 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Fields.php(649): craft\services\Fields->_fields(NULL)
#12 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2178): craft\services\Fields->getAllFields()
#13 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1472): craft\elements\db\ElementQuery->customFields()
#14 /Users/yyy/xxx/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#15 /Users/yyy/xxx/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#16 /Users/yyy/xxx/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#17 /Users/yyy/xxx/vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#18 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1635): craft\db\Query->one(NULL)
#19 /Users/yyy/xxx/vendor/craftcms/cms/src/elements/User.php(461): craft\elements\db\ElementQuery->one()
#20 /Users/yyy/xxx/vendor/yiisoft/yii2/web/User.php(697): craft\elements\User::findIdentity(391)
#21 /Users/yyy/xxx/vendor/craftcms/cms/src/web/User.php(522): yii\web\User->renewAuthStatus()
#22 /Users/yyy/xxx/vendor/yiisoft/yii2/web/User.php(198): craft\web\User->renewAuthStatus()
#23 /Users/yyy/xxx/vendor/doublesecretagency/craft-viewcount/src/ViewCount.php(62): yii\web\User->getIdentity()
#24 /Users/yyy/xxx/vendor/yiisoft/yii2/base/BaseObject.php(109): doublesecretagency\viewcount\ViewCount->init()
#25 /Users/yyy/xxx/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#26 /Users/yyy/xxx/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('view-count', Object(craft\web\Application), Array)
#27 [internal function]: craft\base\Plugin->__construct('view-count', Object(craft\web\Application), Array)
#28 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#29 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('doublesecretage...', Array, Array)
#30 /Users/yyy/xxx/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('doublesecretage...', Array, Array)
#31 /Users/yyy/xxx/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#32 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Plugins.php(948): Craft::createObject(Array, Array)
#33 /Users/yyy/xxx/vendor/craftcms/cms/src/services/Plugins.php(232): craft\services\Plugins->createPlugin('view-count', Array)
#34 /Users/yyy/xxx/vendor/craftcms/cms/src/base/ApplicationTrait.php(1487): craft\services\Plugins->loadPlugins()
#35 /Users/yyy/xxx/vendor/craftcms/cms/src/web/Application.php(99): craft\web\Application->_postInit()
#36 /Users/yyy/xxx/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#37 /Users/yyy/xxx/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#38 [internal function]: yii\base\Application->__construct(Array)
#39 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#40 /Users/yyy/xxx/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#41 /Users/yyy/xxx/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#42 /Users/yyy/xxx/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#43 /Users/yyy/xxx/vendor/craftcms/cms/bootstrap/bootstrap.php(246): Craft::createObject(Array)
#44 /Users/yyy/xxx/vendor/craftcms/cms/bootstrap/web.php(51): require('/Users/davidhel...')
#45 /Users/yyy/xxx/web/index.php(20): require('/Users/davidhel...')
#46 /Users/davidhellmann/.composer/vendor/laravel/valet/server.php(235): require('/Users/davidhel...')
#47 {main}
```

**Comment by vovadyach** [comment] 2022-08-31 20:30
> To be honest, at the very least I see this as an error with that error message, which is a fault of Craft's - if it told you the offending field, it'd make fixing the issue manually so much easier.

Hello,
Could you share how could you fix that?

**Comment by jaspertandy** [comment] 2022-08-31 20:33
> > To be honest, at the very least I see this as an error with that error message, which is a fault of Craft's - if it told you the offending field, it'd make fixing the issue manually so much easier.
> 
> Hello, Could you share how could you fix that?

To just fix it quick I edited the exception code in the vendor directory to tell me more information about the offending field, then edited the YAML to remove what was trying to set it.

**Comment by vovadyach** [comment] 2022-08-31 20:41
> 

Ok, got it. Thank you for the quick response.
