### ISSUE TITLE
Matrix block image setting not saving

### ISSUE THREAD

**Issue by marcustrapp** [craftcms/redactor#91] opened 2018-09-10 19:41 UTC
Description
It appears that when a Redactor field is in a Matrix block, it doesn't retain an embedded image's "Open in New Window" checkbox setting.

Steps to reproduce
- Create a Matrix field with a block that contains a Reactor field.
- Configure the Redactor field to allow image embeds.
- Open an entry with the Matrix field, insert an image.
- Click on the image, select "Edit", enter a URL for the link, check the "Open in New Window" checkbox, and save the entry.
- Leave the page or otherwise reload the entry.
- Reopen the image's Edit window -- all other information will be present, but the "Open in New Window" checkbox will now be unchecked.

Additional info
Craft version: Pro 3.0.23.1
PHP version: 7.0
Database driver & version: Mariadb 10.3
Plugins & versions: Redactor 2.1.6

**Comment by andris-sevcenko** [comment] 2018-10-26 11:46
Unable to reproduce this - most likely was fixed with 2a217d0

**Closed by andris-sevcenko** 2018-10-26 11:46 UTC
