### ISSUE TITLE
Issue with Redactor loosing some formatting when saving the page

### ISSUE THREAD

**Issue by franciurachel** [craftcms/redactor#243] opened 2020-06-30 09:36 UTC
First of all, I am not sure whether it's an issue with Redactor or Craft or both :)
For some users, when on Chrome, but not happening if in Incognito mode, heading formatting does not save, unless pressing enter or space after the text.

1. Create a text
2. Apply h2 formatting
3. Save the page
4. Formatting disappears

Regardless of Purify HTML and Clean Up HTML advanced configuration. (Tried to change it to solve the problem).

Redactor Config:
```
{
  "buttons": ["html", "format", "bold", "italic", "unorderedlist", "orderedlist", "link", "file"],
  "plugins": ["fullscreen"],
  "linkNewTab": true,
  "toolbarFixed": true,
  "formatting": ["h2", "h3", "h4", "h5", "h6", "p"]
}
```

Craft 3.3.01 and 3.2.8.
Redactor 2.3.3.2

**Comment by olets** [comment] 2020-08-20 19:57
This seems to be limited by what plugins are configured.

For example, this has the undesired behavior

```json
{
  "buttons": ["formatting"],
  "formattingAdd": {
    "tester": {
      "title": "tester",
      "api": "module.block.format",
      "args": {
        "tag": "p",
        "attr": {
          "class": "tester"
        },
        "style": {
          "color": "#aaa",
          "text-align": "right"
        },
        "type": "toggle"
      }
    }
  },
}
```

Before save

<kbd><img src="https://user-images.githubusercontent.com/3282350/90816467-5260d300-e2fa-11ea-97f5-6da3a116b16d.png"></kbd>

After save

<kbd><img src="https://user-images.githubusercontent.com/3282350/90816480-57be1d80-e2fa-11ea-9832-0786eea6b615.png"></kbd>

But this works

```json
{
  "buttons": ["formatting"],
  "formattingAdd": {
    "tester": {
      "title": "tester",
      "api": "module.block.format",
      "args": {
        "tag": "p",
        "attr": {
          "class": "tester"
        },
        "style": {
          "color": "#aaa",
          "text-align": "right"
        },
        "type": "toggle"
      }
    }
  },
  "plugins": ["alignment", "fontcolor"]
}
```

After save:

<kbd><img src="https://user-images.githubusercontent.com/3282350/90816532-6b698400-e2fa-11ea-982b-acb1e1acd016.png"></kbd>

That approach isn't a fix for things there isn't a plugin for:

```json
{
  "buttons": ["formatting"],
  "formattingAdd": {
    "tester": {
      "title": "tester",
      "api": "module.block.format",
      "args": {
        "tag": "p",
        "attr": {
          "class": "tester"
        },
        "style": {
          "color": "#aaa",
          "font-size": "70%",
          "font-style": "italic",
          "text-align": "right"
        },
        "type": "toggle"
      }
    }
  },
  "plugins": ["alignment", "fontcolor"]
}
```

before save

![image](https://user-images.githubusercontent.com/3282350/90817455-d8314e00-e2fb-11ea-83a1-d63e3a1f1729.png)

after save

![image](https://user-images.githubusercontent.com/3282350/90817486-e4b5a680-e2fb-11ea-91b3-d676acdbb80e.png)

Moreover —and this feels like an important clue— it appears that the tag limits what can be added. Custom plugin example:

```json
{
  "plugins": ["alignment", "fontcolor", "inlinestyle"]
}
```

```javascript
;(function($R) {
  $R.add('plugin', 'inlinestyle', {
      translations: {
          en: {
              style: 'Style'
          }
      },
      init: function(app) {
          this.app = app
          this.lang = app.lang
          this.toolbar = app.toolbar
          this.styles = {
              mydiv: {
                  title: 'mydiv',
                  args: {
                      tag: 'div',
                      class: 'mydiv',
                      type: 'toggle',
                      style: {
                        background: "blue",
                        color:'#aaa',
                        'font-size': '70%',
                        'font-style': 'italic',
                        'text-align': 'right'
                      }
                  }
              },
              mymark: {
                  title: 'mymark',
                  args: {
                      tag: 'mark',
                      class: 'mymark',
                      type: 'toggle',
                      style: {
                        background: "blue",
                        color:'#aaa',
                        display: 'block',
                        'font-size': '70%',
                        'font-style': 'italic',
                        'text-align': 'right'
                      }
                  }
              }
          }
      },
      start: function() {
          var dropdown = {}
          for (var key in this.styles) {
              var style = this.styles[key]
              dropdown[key] = {
                  title: style.title,
                  api: 'module.inline.format',
                  args: style.args
              }
          }

          var $button = this.toolbar.addButtonAfter('format', 'inline', {
              title: this.lang.get('style')
          })

          $button.setIcon('<i class="re-icon-inline"></i>')
          $button.setDropdown(dropdown)
      }
  })
})(Redactor)
```

Before save:

![image](https://user-images.githubusercontent.com/3282350/90818684-e3d14480-e2fc-11ea-8679-234dda9de183.png)

After save:

![image](https://user-images.githubusercontent.com/3282350/90818839-2561ef80-e2fd-11ea-8eae-f6857e68ae95.png)

**Comment by andris-sevcenko** [comment] 2022-01-26 11:27
This is a duplicate of #237 which has been fixed.

As for the issue raised by @olets - If you haven't disabled the `Remove inline styles` setting for the Redactor field, the configured plugins will be taken into account when stripping the inline styles, so the simplest solution is to disable the setting if you can't cover your required style attributes with plugins.

**Closed by andris-sevcenko** 2022-01-26 11:27 UTC
