### ISSUE TITLE
Adding link in an unordered list removes the first list item and places link on second item

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/redactor#121] opened 2019-02-08 14:40 UTC
Steps to reproduce:

1. Create an unordered list
2. Add a link (to an entry for example) on the first item.
3. Now add a link to an entry on the second link

Result: First item disappears in total and first link gets placed on second link.
Expected: New link on second item

**Comment by andris-sevcenko** [comment] 2019-02-08 15:25
Reopened #104, which is a duplicate of this.

**Closed by andris-sevcenko** 2019-02-08 15:25 UTC
